name: Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle
    
    - run: ./gradlew test --no-daemon
      id: test
      continue-on-error: true

    - run: mkdir -P results-history

    - name: html-reporter-github-pages
      continue-on-error: true
      uses: PavanMudigonda/html-reporter-github-pages@v1.1
      with:
        test_results: ./build/reports/tests/test
        gh_pages: gh-pages
        results_history: results-history

    - name: Publish Github Pages
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: results-history
        keep_files: true 

    - name: Post the link to the report
      uses: Sibz/github-status-action@v1
      with: 
        authToken: ${{ secrets.GITHUB_TOKEN }}
        context: Test report
        state: success
        sha: ${{ github.event.pull_request.head.sha }}
        target_url: ${{ env.GH_PAGES_URL }}/${{ github.run_number }}

    - name: Fail the build if tests failed
      if: steps.test.outcome == 'failure'
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Tests failed!')
